## Multinomial Distributions

### 1. Let's define some basics

In [339]:
def factorial (n):
    '''Takes in a non-negative integer n and returns the factorial of n'''
    factorial = 1
    if n <0:
        return str(n) + " is not in the range"
    else:
        for i in range(1,n+1):
            factorial = factorial*i
        return factorial

In [340]:
def combination(p,r): #choose r-element subsets from p-element subsets
    return factorial(p)//(factorial(r)*factorial(p-r))

In regular combinations, we assume the probability of choosing or not chosing are the same. What about the cases where to choose and not to choose are not the same. For example, in a 4-choice multiple choice test, in how many ways we can select 8 correct answers from 10 questions?

In [341]:
def comb_a_b(a,b,p,r): 
    '''a is the ways to choose the desired outcome 
    b is the ways not to choose the desired outcome
    p is the total number of selections
    r is the number of the occurence of the desired outcome
    '''
    return a**r*b**(p-r)*factorial(p)//(factorial(r)*factorial(p-r))

If we try to answer the above question, a=1, b-=3, r=8, p = 10

In [342]:
print("There are {0} ways to have 8 correct answers in a 10 questions test".format(comb_a_b(1,3,10,8)))

There are 405 ways to have 8 correct answers in a 10 questions test


In both of the questions above, we assumed that we have binary outcomes, to be in the set or not to be in the set. What about the cases that we have ternary outcomes? Let's say we have 3 different colors of marbles in a jar and one from each color and we select n marbles with replacement. How many different ways we have r1 numbers of color 1, r2 numbers of color 2? We can see that there will be n-r1-r2 numbers of color 3, that we do not need to define an r3 variable.

In [343]:
def comb3(n,r1,r2):
    '''n is the number of elements we choose from
    r1 is the number of elements in the first subset
    r2 is the number of elements in the second subset'''
    return factorial(n)//(factorial(r1)*factorial(r2)*factorial(n-r1-r2))

Let's try this function to answer the question. In how many different ways we can select 2 senate members and 3 house members from a class of 10 people given that any student cannot hold two roles. 

In [344]:
# n=10, r1 = 2, r2 = 3
comb3(10,2,3)

2520

We can try a similar formula for choosing 4 mutually exclusive subsets from a set and define comb4 function as:

In [345]:
def comb4(n,r1,r2,r3):
    '''n is the number of elements we choose from
    r1 is the number of elements in the first subset
    r2 is the number of elements in the second subset
    r3 is the number of elements in the third subset'''
    return factorial(n)//(factorial(r1)*factorial(r2)*factorial(r2)*factorial(n-r1-r2-r3))

Let's try when n=9, r1=2, r2=1, r3=3

In [346]:
comb4(9,2,1,3)

30240

Now, we can generalize the definition as choosing r-mutually exclusine subsets from a set with n-elements. Firstly we can define a vector of size r-1 that has the number of occurences we want for each element. Let's name the function as combvec:

In [347]:
import numpy as np
def combvec(n,avec):
    '''n is the size of the set we are choosing from
    avec is the vector of size r-1'''
    if n<np.sum(avec):
        return "combvec cannot be defined"
    else:
        result = factorial(n)
        remainder = n
        for i in list(avec):
            result = result//factorial(i)
            remainder-=i
        return result//factorial(remainder)

Let's try an example:

In [348]:
avec = np.array([1,2,3,3,2])
combvec(11, avec)

277200

## 2. Can we make new triangles similar to Pascal Triangle?

Let's start with defining a Pascal triangle with n-rows:

In [349]:
def Pascal(n): #n is the size of the Pascal's triangle
    for i in range(n+1):
        row_list = []
        for j in range(i+1):
            row_list.append(combination(i,j))
        print(row_list)

Here is an example of Pascal's triangle with size 5

In [350]:
Pascal(5)

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]


Now, we will generate a triangle, where there are a-ways to be chosen, b-ways not to be chosen as:

In [351]:
def Pascal_a_b(n,a,b):
    for i in range(n+1):
        row_list = []
        for j in range(i+1):
            row_list.append(comb_a_b(a,b,i,j))
        print(row_list)

Let's try an example where $a=2, b=1$ and $n=5$

In [352]:
Pascal_a_b(5,2,1)

[1]
[1, 2]
[1, 4, 4]
[1, 6, 12, 8]
[1, 8, 24, 32, 16]
[1, 10, 40, 80, 80, 32]


Not surprisingly each row addition is equal to $(a+b)^i$, where $i$ is the row index and row indices are starting from 0. Now, we will try to make a 3-dimensional Pascal's triangle by using comb3 function.

In [353]:
def Pascal3(n):
    for i in range(n+1):
        row_list = []
        for j in range(i+1):
            row_list.append(comb3(n,(n-i),j))
        print(row_list)

In [354]:
Pascal3(6)

[1]
[6, 6]
[15, 30, 15]
[20, 60, 60, 20]
[15, 60, 90, 60, 15]
[6, 30, 60, 60, 30, 6]
[1, 6, 15, 20, 15, 6, 1]


The above example finds the 6th layer of the 3-dimensional object that all three subsets are equally likely to be chosen. Not surprisingly, the sum of nth layers are always $3^n$. Let's think about the cases where three subsets have some weights as w1, w2, and w3. We need to tweak comb3 function to satisfy this setting:

In [355]:
def comb3_w(n,r1,r2,w1,w2,w3):
    '''n is the number of elements we choose from
    r1 is the number of elements in the first subset
    r2 is the number of elements in the second subset
    w1 is the weight of r1
    w2 is the weight of r2
    w3 is the weight of n-r1-r3'''
    return w1**r1*w2**r2*w3**(n-r1-r2)*comb3(n,r1,r2)

In [356]:
def Pascal3_w(n,w1,w2,w3):
    for i in range(n+1):
        row_list = []
        for j in range(i+1):
            row_list.append(comb3_w(n,(n-i),j,w1,w2,w3))
        print(row_list)

In [357]:
Pascal3_w(3,1,2,3)

[1]
[9, 6]
[27, 36, 12]
[27, 54, 36, 8]


We can observe that the sum of the numbers in $n^{th}$ layer of Pascal3_w function is always $(w1+w2+w3)^n$

For nonnegative w1, w2 and w3 where w1+w2+w3 = 1, comb3_p function can be used to define a trinomial distribution. In this case, let's rename w1 as p1 and w2 as p2 since these numbers represent probabilities. We do not need to define p3, since the probability of the third category will be automatically $1-p1-p2$.

In [358]:
def comb3_p(n,r1,r2,p1,p2):
    '''n is the number of elements we choose from
    r1 is the number of elements in the first subset
    r2 is the number of elements in the second subset
    p1 is the weight of r1
    p2 is the weight of r2'''
    return p1**r1*p2**r2*(1-p1-p2)**(n-r1-r2)*comb3(n,r1,r2) 
# This time we use float division instead of integer division to make sure to have float answers

In [359]:
def Pascal3_p(n,p1,p2):
    for i in range(n+1):
        row_list = []
        for j in range(i+1):
            row_list.append(round(comb3_p(n,(n-i),j,p1,p2),15)) # Python goes weird in 16th digit
        print(row_list)

In [360]:
Pascal3_p(3,0.2,0.4)

[0.008]
[0.048, 0.048]
[0.096, 0.192, 0.096]
[0.064, 0.192, 0.192, 0.064]


Let's answer the following question: The probabilities of a soccer team to win is 0.5 and probability of lose is 0.3 and the probability tie is 0.2. Let's assume the results of the games are independent. What is the probability of this team having 7 wins, 2 lose and 1 tie?

In [361]:
# We need to use comb3_p function with $n=10, r1=7, r2=2, p1=0.5$ and $p2=0.3$
comb3_p(10,7,2,0.5,0.3)

0.050624999999999996

Now, let's question whether these outcomes are good fit for our model. We need to perform a chi-square goodness of fit test

In [362]:
# importing packages 
import scipy.stats as stats 

def gof3(n,r1,r2,p1,p2):
    observed_data = [r1,r2,n-r1-r2] 
    expected_data = [n*p1,n*p2,n*(1-p1-p2)] 
    print(observed_data)
    print(expected_data)
  
  
    # Chi-Square Goodness of Fit Test 
    chi_square_test_statistic, p_value = stats.chisquare( 
    observed_data, expected_data) 
  
    # chi square test statistic and p value 
    print('chi_square_test_statistic is : ' +
      str(chi_square_test_statistic)) 
    print('p_value : ' + str(p_value)) 
  

In [363]:
# Let's test the goodness of fit for the example above:
gof3(10,7,2,0.5,0.3)

[7, 2, 1]
[5.0, 3.0, 2.0]
chi_square_test_statistic is : 1.6333333333333333
p_value : 0.4419022095845254


Now, we can generalize our comb3_p function to find the probabilities for any multinomial probability distributions:

In [364]:
def combvec(n,avec, pvec): 
    '''n is the size of the set we are choosing from
    avec is the observation vector of size r-1
    pvec is the probability vector of size r-1'''
    if n<np.sum(avec) or 1<np.sum(pvec):
        return "combvec cannot be defined"
    else:
        result = factorial(n)
        remainder = n
        coef = 1
        list_a = list(avec)
        list_p = list(pvec)
        for i in range(len(list_a)):
            result = result/factorial(list_a[i])
            remainder-=i
            coef = coef*list_p[i]**list_a[i]
        return coef * result/factorial(remainder)

In [365]:
avec = np.array([1,1,1])
pvec = np.array([0.25,0.25,0.25])
combvec(4,avec, pvec)

0.375

Now we can define goodness of fit for avec and pvec as:

In [366]:
def gofvec(n,avec, pvec):
    observed_data = list(np.append(avec,np.array([n-np.sum(avec)])))
    expected_data = list(n*np.append(pvec,np.array([1-np.sum(pvec)])))
    print(expected_data)
    print(observed_data)
  
    # Chi-Square Goodness of Fit Test 
    chi_square_test_statistic, p_value = stats.chisquare( 
    observed_data, expected_data) 
  
    # chi square test statistic and p value 
    print('chi_square_test_statistic is : ' +
      str(chi_square_test_statistic)) 
    print('p_value : ' + str(p_value)) 

In [367]:
gofvec(4,avec, pvec)

[1.0, 1.0, 1.0, 1.0]
[1, 1, 1, 1]
chi_square_test_statistic is : 0.0
p_value : 1.0


## 3.Define pdf and standard deviation

In [368]:
def binomial_pdf(n,r,p):
    # the point probability of choosing r success when 
    if p>1 or p<0:
        return "probability is not in the range"
    else:
        return combination(n,r)*p**r*(1-p)**(n-r)

In [369]:
def trinomial_pdf(n,r1,r2,p1,p2):
  if p1>1 or p1<0 or p2>1 or p2<0 or p1+p2>1:
    return "probability is not in the range"
  else:
    return comb3(n,r1,r2)*p1**r1*p2**r2*(1-p1-p2)**(n-r1-r2)

In [370]:
def quadrinomial_pdf(n,r1,r2,r3,p1,p2,p3):
  if p1<0 or p2<0 or p3<0 or p1+p2+p3>1:
    return "probability is not in the range"
  else:
    return comb4(n,r1,r2,r3)*p1**r1*p2**r2*p3**r3*(1-p1-p2-p3)**(n-r1-r2-r3)

In [371]:
quadrinomial_pdf(4,1,1,1,0.25,0.25,0.25)

0.09375

In [372]:
def binomial_cdf(n,lower,upper,p):
    binomial_cdf = 0
    for i in range(lower,upper+1):
        binomial_cdf = binomial_cdf + binomial_pdf(n,i,p)
    return binomial_cdf

## 4. Standard deviation and z-score

We can start by defining a standard deviation in a regular binomial distribution as:

In [373]:
def binomial_std(n,p):
    '''n is the sample size and p is the probability of success'''
    return ((n*p)*(1-p))**(1/2)

In [374]:
def z2_score(x,n,p):
    '''How far is x from the mean'''
    return (x-n*p)/binomial_std(n,p)

Now, try to find the distance of an observation from the mean in a trinomial distribution. First, we need to define the standard deviation

In [412]:
gof3(3,0,0,1/3,1/3)

[0, 0, 3]
[1.0, 1.0, 1.0000000000000002]
chi_square_test_statistic is : 5.999999999999998
p_value : 0.049787068367863986


In [375]:
def std_dev3(n,p,r):
    return 3*(n*p*r*(1-p-r))**(1/2)

In [376]:
def z3_score(x,y,n,p,r):
    return ((((x-n*p)/std_dev3(n,p,r))**2 + ((y-n*r)/std_dev3(n,p,r))**2 + ((n-x-y-n*(1-p-r))/std_dev3(n,p,r))**2)/2)**(1/2)

In [377]:
def std_dev4(n,p1,p2,p3):
    return (96*n*p1*p2*p3*(1-p1-p2-p3))**(1/2)

In [378]:
std_dev4(1,0.25,0.25,0.25)

0.6123724356957945

In [379]:
0.6123724356957945**2

0.37499999999999994

In [380]:
import numpy as np
def gauss(x,n):
  return np.sqrt(2/n*np.pi)*np.exp(-2*x**2/n)

In [381]:
gauss(1,2)

0.6520493321732922

In [382]:
def z4_score(x,y,z,n,p,r,q):
    return (((((x-n*p)/std_dev4(n,p,r,q))**2 + ((y-n*r)/std_dev4(n,p,r,q))**2 + ((z-n*q)/std_dev4(n,p,r,q))**2+((n-x-y-z-n*(1-p-q-r))/std_dev4(n,p,r,q))**2)/2)**(1/2))*std_dev4(n,p,r,q)
print(z4_score(0,0,0,4,(1/4),(1/4),(1/4)))

2.449489742783178


In [383]:
std_dev4(1,0.25,0.25,0.25)

0.6123724356957945

In [384]:
import numpy as np
def normal(avec):
  return avec/np.sum(avec)

def distance(nvec, pvec):
  return np.sqrt(np.sum(((pvec - nvec)**2)/2)) #why do you divide by two? I guess the distances between the unit vecors are sqrt(2) 

In [385]:
a = np.array([0.25,0.25,0.25,0.25])
b = np.array([0,0,0,1])
distance(a,b)

0.6123724356957945

In [386]:
normal(b)

array([0., 0., 0., 1.])

In [387]:
def vmean(avec):
  return np.ones(np.size(avec))/np.sum(np.ones(np.size(avec)))

In [388]:
vmean(b)

array([0.25, 0.25, 0.25, 0.25])

In [389]:
np.ones(np.size(b))

array([1., 1., 1., 1.])

In [390]:
def z_score(avec):
    return distance(avec, np.sum(avec)*vmean(avec))

In [391]:
k = np.array([6,18])
l = np.array([1,2,3])
m = np.array([0,0,0,0,1])
n = np.array([0,0,0,1])

In [392]:
z_score(m)

0.6324555320336759

In [393]:
z_score(n)

0.6123724356957945

In [394]:
z_score(m)**2

0.4

In [395]:
def std_dev5(n,p1,p2,p3,p4):
    return (1250*n*p1*p2*p3*p4*(1-p1-p2-p3-p4))**(1/2)

In [396]:
std_dev5(1,0.2,0.2,0.2,0.2)

0.632455532033676

In [397]:
def std_dev6(n,p1,p2,p3,p4,p5):
    return (1250*n*p1*p2*p3*p4*p5*(1-p1-p2-p3-p4-p5))**(1/2)

In [398]:
m6 = np.array([0,0,0,0,0,1])

In [399]:
z_score(m6)

0.6454972243679029

In [400]:
0.6454972243679029**2

0.4166666666666668

In [401]:
k2 = np.array([0,1])
k3 = np.array([0,0,1])
k4 = np.array([0,0,0,1])
k5 = np.array([0,0,0,0,1])
k6 = np.array([0,0,0,0,0,1])
k7 = np.array([0,0,0,0,0,0,1])
k8 = np.array([0,0,0,0,0,0,0,1])

In [402]:
z_score(k2)

0.5

In [403]:
z_score(k8)**2

0.43750000000000006

In [404]:
0.43750000000000006*16

7.000000000000001

In [405]:
z_score(k3)**2

0.3333333333333334

In [406]:
def std_dev6(n,p1,p2,p3,p4,p5):
    return ((6**5)*(5/2)*n*p1*p2*p3*p4*p5*(1-p1-p2-p3-p4-p5))**(1/2)

In [407]:
std_dev6(1,1/6,1/6,1/6,1/6,1/6)

0.6454972243679031

In [408]:
z_score(k6)

0.6454972243679029

In [ ]:
#this code may not work
#def st_devn(n,p1,p2,p3,p4,pn):
#   return ((n**(n-1))*((n-1)/2)*p1*....)